### PR TITLE
Run Prettier

### PR DESCRIPTION
**Pull request by thewilloftheshadow**
Initial run of prettier, bypassing eslint

### CODE REVIEW

**Comment by not-so-smart** [comment]
is this up-to-date with main?

**Comment by thewilloftheshadow** [comment]
GitHub Desktop says it is

**Comment by not-so-smart** [comment]
I'm hesitant to merge this when there's so many open branches, because almost 100% of them will have merge conflicts with this one. Once everything is closed, we can merge main back into this branch and run prettier again.

image

**Comment by thewilloftheshadow** [comment]
I love how a lot of it is mine 😂😂 

Sounds good to me

**Pull request closed without merging**
